### ISSUE TITLE
configure github actions to build + deploy

### ISSUE THREAD

**Issue by codykrieger** [codykrieger/krieger.io#9]
- https://github.com/peaceiris/actions-hugo
- https://github.com/peaceiris/actions-gh-pages

something like:

```yaml
name: build + deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.75.1'
          extended: true
    - run: hugo --minify
    - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          cname: new.krieger.io
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
```
